### PR TITLE
Data Request

### LINKED ISSUE #18: Parsing of tables (data request)
Builds the data request information from the tables, making sure there is not variable repetition and correct merging of the information spread across the different tables.

https://github.com/FESOM/seamore/blob/7725366f7b68ea3824ac6baa500ea49531722b72/lib/data_request.rb#L7

The file consists in 4 classes:
- [x] `DataRequest`: responsible for managing variables and their associated metadata across **multiple CMIP6 tables**.
     - [x] Frequency mappings: map a frequency name with a numeric frequency (maybe this is better in a separate file?
- [x] `DataRequestVariable`: represents a single variable and its associated metadata. It can merge multiple `TableVarEntry`s into `DataRequestVariable` object
- [x] `TableVarEntry`: represents a **single** entry for a variable in a table.
- [x] `DataRequestTable`: represents a single CMIP6 table and its metadata.

The overall design ensures that variables are merged correctly across multiple tables, providing a unified interface to query variables and their metadata.

### Crappy ~UML
```mermaid
flowchart LR

    subgraph DataRequest
        subgraph DRinitialize[initialize]
            direction TB
            table_initialization
            --> var_initialization
            --> for_vars[for v in vars]
            --> if_v_exists[    if v exists]
            --> if_v_!exists[    else]
        end
    end
    subgraph DataRequestVariable
        new_from_table_var_entry
        --> DRVinitialize[initialize]
        merge_table_var_entry
    end
    subgraph TableVarEntry
        TVEinitialize[initialize]
    end
    subgraph DataRequestTable
        DRTinitialize[initialize]
        variable_entries
    end

    table_initialization --> DRTinitialize
    var_initialization --> variable_entries
    variable_entries --> TVEinitialize
    if_v_exists --> merge_table_var_entry
    if_v_!exists --> new_from_table_var_entry
```

### PR DESCRIPTION
**Pull request by pgierz**
This will provide functionality to merge together various Tables/Data Requests and connect it so that one Rule has all information linked to a specific Data Request Variable.

Will close #18

### CODE REVIEW

**Comment by pgierz** [comment]
This currently implements the same logic as in the Ruby tool.

**Comment by pgierz** [comment]
There are two last things here that I would be happy for @siligam to look at:

- [ ] How to handle same variables with different requested frequency methods (mean vs instant)
- [ ] Removing hard-coded tables to exclude

Otherwise this is good to go and duplicates the Ruby logic. To what extent and how we use this is not yet decided.

**Comment by pgierz** [comment]
OK, this one is good to go from my side. Please review and make suggestions for improvements.

**Review by siligam — DISMISSED** [review]
Looks good.

**Comment by pgierz** [comment]
God mode used for this merge.

**Pull request merged**
